version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "34:98:4e:a6:41:94:50:9d:6c:9b:cd:85:97:00:9c:8f"
      - run:
          command: |
            git config user.email "ooz@users.noreply.github.com"
            git config user.name "ooz"
      - run:
          command: |
            make deploy
